/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Mantenimiento;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


public class JFrameMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAtencionMedica
     */
    public JFrameMantenimiento() {
        initComponents();
            Limpiar();
            
        this.setResizable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoMantenimiento = new javax.swing.ButtonGroup();
        jPanelGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDC = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldCedulaCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreMecanico = new javax.swing.JTextField();
        jPanelDM = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTrabajosRealizados = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTipoVehiculo = new javax.swing.JComboBox<>();
        jButtonGuardar = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonPreventivo = new javax.swing.JRadioButton();
        jRadioButtonCorrectivo = new javax.swing.JRadioButton();
        jTextFieldRepuestoUtilizado = new javax.swing.JTextField();
        jLabelRepuestoUtilizado = new javax.swing.JLabel();
        jLabelValorRepuesto = new javax.swing.JLabel();
        jTextFieldValorRepuesto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListServiciosOpcionales = new javax.swing.JList<>();
        jButtonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(875, 640));
        setResizable(false);

        jPanelGeneral.setBackground(new java.awt.Color(35, 35, 35));
        jPanelGeneral.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("BatmanForeverAlternate", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("WITHCARS");

        jPanelDC.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)), "DATOS DEL CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 14), new java.awt.Color(0, 255, 204))); // NOI18N
        jPanelDC.setForeground(new java.awt.Color(102, 102, 102));

        jLabelNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNombre.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("CEDULA");

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("MECANICO RESPONSABLE");

        javax.swing.GroupLayout jPanelDCLayout = new javax.swing.GroupLayout(jPanelDC);
        jPanelDC.setLayout(jPanelDCLayout);
        jPanelDCLayout.setHorizontalGroup(
            jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDCLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombreMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDCLayout.createSequentialGroup()
                        .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDCLayout.setVerticalGroup(
            jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNombre)
                        .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreMecanico))
                .addGap(9, 9, 9))
        );

        jPanelDM.setBackground(new java.awt.Color(51, 51, 51));
        jPanelDM.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)), "DETALLES DEL MANTENIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 14), new java.awt.Color(0, 255, 204))); // NOI18N

        jTextAreaDiagnostico.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaDiagnostico.setColumns(20);
        jTextAreaDiagnostico.setLineWrap(true);
        jTextAreaDiagnostico.setRows(5);
        jTextAreaDiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIAGNOSTICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(jTextAreaDiagnostico);

        jTextAreaTrabajosRealizados.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaTrabajosRealizados.setColumns(20);
        jTextAreaTrabajosRealizados.setLineWrap(true);
        jTextAreaTrabajosRealizados.setRows(5);
        jTextAreaTrabajosRealizados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRABAJOS REALIZADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(jTextAreaTrabajosRealizados);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("TIPO DE VEHICULO");

        jComboBoxTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camioneta", "Furgon", "Colectivo" }));

        jButtonGuardar.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FECHA DE MANTENIMIENTO");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE MANTENIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jRadioButtonPreventivo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupTipoMantenimiento.add(jRadioButtonPreventivo);
        jRadioButtonPreventivo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPreventivo.setText("PREVENTIVO");

        jRadioButtonCorrectivo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroupTipoMantenimiento.add(jRadioButtonCorrectivo);
        jRadioButtonCorrectivo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCorrectivo.setText("CORRECTIVO");
        jRadioButtonCorrectivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonCorrectivoItemStateChanged(evt);
            }
        });

        jTextFieldRepuestoUtilizado.setEnabled(false);

        jLabelRepuestoUtilizado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRepuestoUtilizado.setText("REPUESTOS UTILISADOS");

        jLabelValorRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorRepuesto.setText("VALOR DE REPUESTOS");

        jTextFieldValorRepuesto.setToolTipText("");
        jTextFieldValorRepuesto.setEnabled(false);
        jTextFieldValorRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorRepuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorRepuesto)
                    .addComponent(jLabelRepuestoUtilizado)
                    .addComponent(jRadioButtonPreventivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCorrectivo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldRepuestoUtilizado)
                        .addComponent(jTextFieldValorRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPreventivo)
                    .addComponent(jRadioButtonCorrectivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRepuestoUtilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRepuestoUtilizado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorRepuesto))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jListServiciosOpcionales.setBackground(new java.awt.Color(204, 204, 204));
        jListServiciosOpcionales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SERVICIOS ADICIONALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jListServiciosOpcionales.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lavado", "Alineacion", "Pintar", "Inflar llanta" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListServiciosOpcionales);

        jButtonVolver.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N
        jButtonVolver.setText("VOLVER");
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelDMLayout = new javax.swing.GroupLayout(jPanelDM);
        jPanelDM.setLayout(jPanelDMLayout);
        jPanelDMLayout.setHorizontalGroup(
            jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDMLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanelDMLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDMLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGuardar)
                        .addGap(246, 246, 246)
                        .addComponent(jButtonVolver)))
                .addContainerGap())
        );
        jPanelDMLayout.setVerticalGroup(
            jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDMLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDMLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar))
                    .addGroup(jPanelDMLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonVolver)))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                        .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(381, 381, 381))))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Mantenimiento man = new Mantenimiento();
    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        // TODO add your handling code here:
       if(jTextFieldNombreCliente.getText().equals("")||jTextFieldCedulaCliente.getText().equals("")||jTextFieldNombreMecanico.getText().equals("")||jTextAreaDiagnostico.getText().equals("")||jTextAreaTrabajosRealizados.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Por favor llenar todos los datos solicitados");
       }else{
           String TipoMan;
           if (jRadioButtonCorrectivo.isSelected()){
               TipoMan=(String)jRadioButtonCorrectivo.getText();
           }else{
               TipoMan = (String)jRadioButtonPreventivo.getText();
           }
           
           double ValorRepuesto;
           
           ValorRepuesto= Double.parseDouble(jTextFieldValorRepuesto.getText());
           String pago;
           DecimalFormat df = new DecimalFormat("0.00");
           pago = df.format((man.Calcular((String)jComboBoxTipoVehiculo.getSelectedItem(),TipoMan,jListServiciosOpcionales.getSelectedValuesList())+ValorRepuesto*1));
         JOptionPane.showMessageDialog(this,"El precio a pagar por la reparacion de "+(String)jComboBoxTipoVehiculo.getSelectedItem()+" es de "+pago);
        man = new Mantenimiento(jTextFieldNombreCliente.getText(), jTextFieldCedulaCliente.getText(),jTextFieldNombreMecanico.getText(), (String)jComboBoxTipoVehiculo.getSelectedItem(), jTextAreaDiagnostico.getText(), jTextAreaTrabajosRealizados.getText(), jDateChooser1.getDate(), TipoMan, jTextFieldRepuestoUtilizado.getText(), ValorRepuesto,jListServiciosOpcionales.getSelectedValue());
        JOptionPane.showMessageDialog(this,"Registro guardado con ¡exito!");
        Limpiar();
       }
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jRadioButtonCorrectivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonCorrectivoItemStateChanged
        // TODO add your handling code here:
        if (jRadioButtonCorrectivo.isSelected()){
            jLabelRepuestoUtilizado.setVisible(true);
            jLabelValorRepuesto.setVisible(true);
            jTextFieldRepuestoUtilizado.setVisible(true);
            jTextFieldValorRepuesto.setVisible(true);
            jTextFieldRepuestoUtilizado.setEnabled(true);
            jTextFieldValorRepuesto.setEnabled(true);
        }else{
            jLabelRepuestoUtilizado.setVisible(false);
            jLabelValorRepuesto.setVisible(false);
            jTextFieldRepuestoUtilizado.setVisible(false);
            jTextFieldValorRepuesto.setVisible(false);
            jTextFieldRepuestoUtilizado.setEnabled(false);
            jTextFieldValorRepuesto.setEnabled(false);
            jTextFieldRepuestoUtilizado.setText("");
            jTextFieldValorRepuesto.setText("");
        }
    }//GEN-LAST:event_jRadioButtonCorrectivoItemStateChanged

    private void jTextFieldValorRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorRepuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorRepuestoActionPerformed

    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        // TODO add your handling code here:
        dispose();
        Seleccion sel = new Seleccion();
        sel.setVisible(true);
    }//GEN-LAST:event_jButtonVolverMouseClicked

    public void Limpiar(){
        jTextFieldNombreCliente.setText("");
        jTextFieldCedulaCliente.setText("");
        jTextFieldNombreMecanico.setText("");
        jComboBoxTipoVehiculo.setSelectedIndex(0);
        jTextAreaDiagnostico.setText("");
        jTextAreaTrabajosRealizados.setText("");
        jTextFieldRepuestoUtilizado.setText("0");
        jTextFieldValorRepuesto.setText("0");
        jRadioButtonCorrectivo.setSelected(true);
        jListServiciosOpcionales.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoMantenimiento;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxTipoVehiculo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRepuestoUtilizado;
    private javax.swing.JLabel jLabelValorRepuesto;
    private javax.swing.JList<String> jListServiciosOpcionales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDC;
    private javax.swing.JPanel jPanelDM;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JRadioButton jRadioButtonCorrectivo;
    private javax.swing.JRadioButton jRadioButtonPreventivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDiagnostico;
    private javax.swing.JTextArea jTextAreaTrabajosRealizados;
    private javax.swing.JTextField jTextFieldCedulaCliente;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreMecanico;
    private javax.swing.JTextField jTextFieldRepuestoUtilizado;
    private javax.swing.JTextField jTextFieldValorRepuesto;
    // End of variables declaration//GEN-END:variables
}
